import type { Metadata } from "next";
import Head from "next/head"; // Import the Head component from next/head
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Preconnect to external domains */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="true" />
        
        {/* Import the font */}
        <link 
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" 
          rel="stylesheet" 
        />
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}
